### PR TITLE
Add Instawork app

### PR DESCRIPTION
**Pull request by PunitGr**
Hello, @adamstep, @lalitpatel please review this.
You can check the live app at [https://punitgr.github.io/task-home/](https://punitgr.github.io/task-home/).

Cheers

### CODE REVIEW

**Comment by lalitpatel** [comment]
Hi Punit, Thanks for working on this. can you please add the following members as reviewers: @adamstep, @arghav

**Comment by PunitGr** [comment]
Hi @lalitpatel, sure. I've invited you guys as collaborators. As soon as they accept the invite, I will add them as reviewers.

**Comment by adamstep** [comment]
Hi @PunitGr , overall the app works well. One suggestion though: the assignment description mentioned that you shouldn't use local state in components, but I see you're doing that for some of the screens. Can you update the code to handle all state in Redux?

**Comment by PunitGr** [comment]
Sure thing. I'm on it. Thanks for the feedback. 👍

**Comment by PunitGr** [comment]
Hi @adamstep, I have updated the changes you suggested. Can you please review the changes?
Thanks!

**Pull request merged**
